services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  consul:
    image: consul:1.15
    container_name: consul
    restart: always
    ports:
      - "8500:8500"      # Consul UI
    command: agent -dev -client=0.0.0.0
    networks:
      - backend

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  postgres_data:


networks:
  backend: